### ISSUE TITLE
Plans to add support for VBScript?

### ISSUE THREAD

**Issue by terremoth** [mrpapercut/wscript#7]
I wish it could run someway vbscript also and trace it informations.
Do you have any plans for one day implement? Or do you have any idea how this can be done?

**Comment by mrpapercut** [comment]
This project is no longer maintained by me. See #6 for more information

I think VBScript support is unlikely with this codebase. The reason this "emulator" works for WScript is because WScript is a flavor of Javascript, so I only had to overcome the differences between them to get WScript to run in Javascript. For VBScript one would need to write a full language parser, and then convert it to another language so it can run and be traced. Absolutely doable, but unlikely

**Comment by terremoth** [comment]
thanks!
